POST http://127.0.0.1:8000/signup/ Content-Type: application/json

{ "username": "Lipe1", "password": "Pass1234!", "email": "Lipe1@mail.com" }



POST http://127.0.0.1:8000/login Content-Type: application/json

{ "username": "Lipe", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json 
Authorization: Token 75ed8cd3a9ed000319afbef9aab75580b814ac44